spring:
  application:
    name: demo
  kafka:
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 100
      enable-auto-commit: true
      auto-offset-reset: earliest
      group-id: test-consumer-group
    bootstrap-servers: 10.1.10.177:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      buffer-memory: 33554432
      batch-size: 16384
      retries: 0
server:
  port: 8089

pocket:
  datasource:
    serverId: 101
    node:
      - url: jdbc:mysql://localhost:3306/biscuits_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        nodeName: mysql-01
        driverName: com.mysql.cj.jdbc.Driver
        showSql: true
        user: root
        password: root
        poolMiniSize: 10
        poolMaxSize: 100
        timeout: 1000
        cacheSize: 1000
        session: biscuits,demo
biscuits:
  token:
    secret: shinow
    expiration: 600000
    refreshTime: 300000
    tokenHead: Bearer
  filter:
    excludeUrlPatterns: /login,/register
